### ISSUE TITLE
Liscense Clarification Question

### ISSUE THREAD

**Issue by maxfridbe** [flydelabs/flyde#102]
Making the editor agpl, not only means that fixes are sent upstream. but if you embedd it in a site , that site has to also be agpl compatible, was this part done intentionaly? Or am I interperating it wrong somehow.

**Comment by GabiGrin** [comment]
@maxfridbe Hey, yes, that's right
Anything needed to run Flyde flows is MIT, but to use the editor itself, your project must comply with Agpl.
Embedding Flyde as a "scripting" language in other products is a potential monetization angle for Flyde, along with other potential projects such as https://www.trigg.dev. It might change to MIT in the future, but this is the status for now.

It's still super early days for Flyde so I'd love to provide a more permissive license to your use-case. Feel free to catch me on [Discord](https://www.flyde.dev/discord/)
