### ISSUE TITLE
🐛 Bug Report: cannot remove connections 

### ISSUE THREAD

**Issue by hmachefe** [flydelabs/flyde#107]
Hey, I'm trying to remove a connection between 2 nodes but can't select the connection to remove it.
Tryting to "hook" the wire with my mouse (click) always unsuccessfully. 
Please have a look at the enclosed witnessing movie

https://github.com/flydelabs/flyde/assets/4142280/fde14d9e-f2dd-431d-8b29-33518ff7b3f4

**Comment by GabiGrin** [comment]
Thanks for the report @hmachefe!
Removing connections is indeed far from ideal now - you need to select the input and output of the existing connection to undo it.

For those looking to help, 2 possible solutions:
1. a context menu on the connections that allows deleting (code should be there, it probably stopped working in a recent blueprint upgrade)
2. allowing selecting the connection and deleting it using the delete/backspace hotkey - in that case, the selection menu (the bottom bar that appears when instances are selected) should reflect that and also allow removing from there
