### ISSUE TITLE
pnpm start:'npm run dev' is  terminated with exit code: 1. 

### ISSUE THREAD

**Issue by akim-muto** [flydelabs/flyde#123]
Hi!

I tried to prepare a development environment on windows 10 and when I tried to `pnpm start`, the `npm run dev` command terminated with exit code: 1. Editor dev was Failed as follows.
```
D:\project\flyde\editor:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @flyde/editor@0.2.62 dev: WDS_SOCKET_HOST=localhost DANGEROUSLY_DISABLE_HOST_CHECK=true FAST_REFRESH=false PUBLIC_URL=/ REACT_APP_FLYDE_MODE=development FORCE_ENV=production react-scripts start
Exit status 1
```
There was a warning at the time of `pnpm i`
```
WARN  Failed to create bin at D:\project\flyde\editor\node_modules\.bin\flyde. The source file at D:\project\flyde\dev-server\dist\cli.js does not exist.
 WARN  Failed to create bin at D:\project\flyde\flow-editor\node_modules\.bin\flyde. The source file at D:\project\flyde\dev-server\dist\cli.js does not exist.
 WARN  Failed to create bin at D:\project\flyde\website\node_modules\.bin\flyde. The source file at D:\project\flyde\dev-server\dist\cli.js does not exist.
 WARN  Failed to create bin at D:\project\flyde\vscode-extension\node_modules\.bin\flyde. The source file at D:\project\flyde\dev-server\dist\cli.js does not exist.
editor postinstall$ node dependencies-patch/index.js || true
[12 lines collapsed]
│     at Object.<anonymous> (D:\project\flyde\editor\dependencies-patch\index.js:26:5)
│     at Module._compile (node:internal/modules/cjs/loader:1241:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
│     at Module.load (node:internal/modules/cjs/loader:1091:32)
│     at Module._load (node:internal/modules/cjs/loader:938:12) {
│   errno: -4058,
│   code: 'ENOENT',
│   syscall: 'open',
│   path: 'D:\\project\\flyde\\editor\\node_modules\\webpack\\lib\\web\\JsonpChunkLoadingRuntimeModule.js'
│ }
└─ Done in 81ms
```
Trying to open `D:\\project\\flyde\\editor\\node_modules\\webpack\\lib\\web\\JsonpChunkLoadingRuntimeModule.js`, but when` pnpm i `exit, there is no `webpack` in the `flyde/editor/node_modules` directory.
Instead, in the `dependencies-patchdependencies-patch` directory `webpack/lib/web/JsonpChunkLoadingRuntimeModule.js` exists.

Is it correctiry specify path in the `dependencies-patchdependencies-patch` directory?

**Comment by GabiGrin** [comment]
@akim-muto I'm looking into it now
If you've found anything new since, do share :)

**Comment by GabiGrin** [comment]
@akim-muto  update - I manage to recreate another issue when running a clean clone. 
Can you try the following:
1. `pnpm install`  -> installs deps so it can be built (step 2). Warning will be emitted due to missing "cli.js" files as they were not built
2. `pnpm run build` -> ensures `dist/cli.js` exists
3. `pnpm install` -> now it'll link everything again
4. `pnpm start` -> should open VSCode with `pnpm run dev` in a terminal

**Comment by akim-muto** [comment]
I did it!


1, Build stops in the middle.` rm` command is not supported by PowerShell.
2, I've tried to use [coreutils](https://github.com/uutils/coreutils) to make it usable, but I get an error at the editor. I'm not sure exactly where the error is, as it seems to be loading asynchronously or something.
3, Same result with MinGW bash that comes with the desktop version of Git.
4, Build succeeds on ubuntu on wsl2. But postinstall script fails in` pnpm install`.
It still says` flyde/editor/node_modules/webpack/lib/web/JsompChunkLoadingRuntimeModul.js` is missing.
5, Here, for now, `pnpm start` is confirmed to work.
6. `pnpm run dev` started failed due to directory settings at startup. Moved to the root directory of the project and `run dev` again. failed.
7, `/flyde/editor/dependencies-patch/webpack/lib/web/JsonpChunkLoadingRuntimeModule.js`
file run in node. I get pissed off with dependencies.
8. Add the webpack dependency to package.json in the edttor directory and run pnpm `install`.
9, postinstall script succeeded!
10, but `run dev` fails.
12, installed chrome on WSL because it seems to be trying to start a browser in WSL and failing, and installed what will become Xserver on the Windows side.
13, moved!


Conclusion:
- On Windows, wsl2 is recommended for now, and clone to the wsl2 directory.
- If you use wsl2, it won't work unless there is a browser on the wsl2 side that tries to start with run dev.
- The postinstall script during install cannot resolve the dependency without dependency webpack, However, I am not sure if the run dev failed because the postinstall script failed or the browser failed to start.
- Also, I forgot to mention before that pnpm install is recommended via use corepack.

So, there are still some suspicious things, like the browser started by run dev failing to access the site, but after modifying the BudlePasth source, I was even able to confirm that the existing stdlib MacroEditor does not work locally in Flyde's development repository!
I will do a simple refactoring of stdlib as planned.

**Comment by GabiGrin** [comment]
@akim-muto  awesome work! I need to spend some time on a window machine trying to set it up. 
What can be taken from your process and moved to docs/code/scripts?

Perhaps the best solution here is to set up a docker based development container.

Regarding MacroEditor not working locally - weird, can you see why? it works here

**Comment by akim-muto** [comment]
I'm sorry for the confusion, I was not talking about a new bug, I was talking about the #120 work.

I guess I can put Doc that confirmed it works on Windows with wsl and would note that precautions.
Also, what is your decision about installing the webpak package in the editor directory to resolve postinstall?

**Comment by akim-muto** [comment]
PS: In the run dev command in the root directory, is it possible to not stop the script even if it cannot be started browser?

If I write a note in the documentation that should install a browser on the wsl side, we will be asking you to install Xserver on Windows, which I don't know much about use Xserver myself.

**Comment by akim-muto** [comment]
ps:I was not able to access the server on the wsl side, and after adding `localhostForwarding=True` to `.wslconfig` in user home, I was able to access it.

**Comment by GabiGrin** [comment]
thanks for the update @akim-muto, I'll be referencing this issue on the contributing guide and close this for now
