### ISSUE TITLE
Local component library broken since v0.102.2

### ISSUE THREAD

**Issue by trustmaster** [flydelabs/flyde#138]
I'm getting

```
TS5109: Option 'moduleResolution' must be set to 'NodeNext' (or left unspecified) when option 'module' is set to 'NodeNext'
```

when trying to use a local `.flyde.ts` component library. I don't recall this happening with previous Flyde versions.

I've added a local `tsconfig.json` file to try fixing it:

```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext"
  }
}
```

but it had no effect.

Using Flyde `v0.102.2` in VSCode.

**Comment by trustmaster** [comment]
@GabiGrin I've tested all previous extension versions. The problem was introduced in the `0.102.2` update, most likely with the TypeScript upgrade. Rolling back to `0.102.0` fixes it.

**Comment by GabiGrin** [comment]
@trustmaster thanks for the report! what typescript version is the project your custom node is under using?

**Comment by trustmaster** [comment]
None. It's a stub for Pyflyde, it doesn't even have node_modules.

**Comment by GabiGrin** [comment]
@trustmaster I see, investigating now
Meanwhile, you can try stripping types and using `flyde.js` extension and it should work

**Comment by trustmaster** [comment]
Thanks for the tip @GabiGrin! Do you think it's a good idea to use `flyde.js` stubs instead of `flydet.ts` in general for Pyflyde? Are there any disadvantages?

**Comment by GabiGrin** [comment]
@trustmaster sure thing!
Given you're using it as a stub, I'd use `.js` to keep it simpler

Regardless, I was able to recreate the issue and found a fix! Thanks so much

**Comment by GabiGrin** [comment]
@trustmaster `0.102.3` was published now and should appear in VSCode in ±20 mins, if you wanna try and avoid changing to .js
