### ISSUE TITLE
Node connection Error

### ISSUE THREAD

**Issue by akim-muto** [flydelabs/flyde#145]
Dragging a node to connect it results in an error.
Perhaps the onMouseEnter / onMouseLeave processing is not working properly, but I am not sure of the details yet.

**Comment by GabiGrin** [comment]
@akim-muto thanks for report! I'm seeing an error being thrown, but the feature works. 
Are you trying on a local development setup? if so, errors are more prominent there, but it should work on any of the latest releases.

Regardless, I'll fix the error :)
