### ISSUE TITLE
The web site's link is incorrect.

### ISSUE THREAD

**Issue by akim-muto** [flydelabs/flyde#158]
The link address on the "Edit this page" is to the template on facebook repo.
The same applies to other pages.

https://www.flyde.dev/docs/#getting-started

**Comment by GabiGrin** [comment]
@akim-muto  thanks for reporting!

**Comment by akim-muto** [comment]
@GabiGrin 
Hey! link is as below now.
"/docs/docs/"

![image](https://github.com/user-attachments/assets/9cae98e5-1967-4dc3-a017-ebd56bcb53f9)
