### ISSUE TITLE
Duplicate entries when using custom component libraries

### ISSUE THREAD

**Issue by trustmaster** [flydelabs/flyde#161]
I'm using Flyde with custom components declared in `.flyde.ts` files. One annoying issue is that modules get duplicated as many times as the number of nodes they contain in the "Current project" menu:

<img width="845" alt="Screenshot 2024-09-22 at 12 10 12" src="https://github.com/user-attachments/assets/33c3d13a-aea9-4dc7-8cf3-cf6959ac24cd">

For example, you can reproduce it if you clone https://github.com/trustmaster/pyflyde and open [examples/HelloPy.flyde](https://github.com/trustmaster/pyflyde/blob/main/examples/HelloPy.flyde).

**Comment by GabiGrin** [comment]
@trustmaster weird! will take a look soon

**Comment by GabiGrin** [comment]
@trustmaster re-opening this as v0.105.0 seems not to be fixed

**Comment by trustmaster** [comment]
@GabiGrin is there a quick way I can test it?

**Comment by GabiGrin** [comment]
@trustmaster extension version `0.105.2` was released now
it usually takes 10-20 minutes to appear in VSCode

let me know if it solves it!

**Comment by trustmaster** [comment]
Works like a charm! Thank you for fixing it!

**Comment by GabiGrin** [comment]
Of course, stupid bug to begin with! thanks for reporting 🙏
