### ISSUE TITLE
Not available on open-vsx.org

### ISSUE THREAD

**Issue by abdulhakam** [flydelabs/flyde#176]
Hi, I found this project some time ago, tried installing it, it was not available on open-vsx.org and hence could not use it on my code editors( I use windsurf, cursor, AND vscodium at the same time configured for different kinds of projects/languages) and vscodium is my main code editor for js/ts projects which use open-vsx.org. the others are based on it so. can you please add flyde extension to openvsx so that non-vscode users can install and try it?

thank you for such an awesome project.

**Comment by GabiGrin** [comment]
Thanks for pointing that out! I'll look into it and update.

**Comment by GabiGrin** [comment]
@abdulhakam quick update - just filed a request to own the Flyde namespace on the open-vsx repo - https://github.com/EclipseFdn/open-vsx.org/issues/3231
Once they approve I hope I'll be able to go through the publication process
![Screenshot 2024-12-22 at 22 28 21](https://github.com/user-attachments/assets/039d22a8-a206-4ee7-a679-52bdffbb4ffc)

Meanwhile, can you try downloading from https://marketplace.visualstudio.com/items?itemName=flyde.flyde-vscode&ssr=false#overview?

**Comment by GabiGrin** [comment]
hey @abdulhakam  https://open-vsx.org/extension/flyde/flyde-vscode check it out :)
