### ISSUE TITLE
Browser runtime

### ISSUE THREAD

**Issue by linonetwo** [flydelabs/flyde#28]
How to run a graph in the browser?

The doc in https://www.flyde.dev/docs/StdLib/ might be misleading, it implies that flyde can only run in the nodejs side, because StdLib includes filesystem node.

Also, how to load nodes lib in the browser? I would like to use esm to load a node lib on the fly, and "register" the node in to the runtime, the load a graph.

**Comment by GabiGrin** [comment]
I believe Flyde's strength is in backend-related tasks, therefore the Node.js focus on the StdLib and docs.

However, Flyde's core is runtime agnostic, and I'll be able to quickly accommodate frontend usages if they prove valuable.

On the "core" level, Flyde is not aware of the StdLib, so anything you pass to it will be referencable in Visual Parts. 

In lue of the official documentation, here's how you could do it:
1. Bundle using webpack, with the [Flyde loader](https://github.com/FlydeHQ/flyde/blob/main/runtime/webpack-loader.js) - example from the website: https://github.com/FlydeHQ/flyde/blob/main/website/docusaurus.config.js#L13
2. Use it to load a visual flow:  https://github.com/FlydeHQ/flyde/blob/main/website/src/pages/playground/debounce-throttling.tsx#L21
3. It will load any existing dependencies that are defined in the visual flow, and then you can pass it to the `execute` function: https://github.com/FlydeHQ/flyde/blob/main/website/src/pages/playground/_PlaygroundTemplate/PlaygroundTemplate.tsx#L107
