### ISSUE TITLE
Core terminology: Rename "Parts" to something else

### ISSUE THREAD

**Issue by GabiGrin** [flydelabs/flyde#33]
Candidates:
1. Nodes
2. Components

Any suggestions are welcome

**Comment by linonetwo** [comment]
Oh, I didn't realize this, i think i use the term node a lot in our discussion.

Also despite kind of outdated, noflo Still has manything we can learn from, including the terminology.

**Comment by GabiGrin** [comment]
Yeah, me too :)
"Node" is indeed the terminology many platforms use (NoFlo, NodeRed and more) but I feel it doesn't tell the whole story.
A node is merely a
> a point at which lines or pathways or branch; a central or connecting point
Which feels too simplistic for what it is doing in such visual programming systems.
With Flyde (and also others) it also has logic, so I'm more inclined to "Component". But "Component" is usually referred to frontend components

Being unable to decide, I started with "Part" which is from one hand awful meaning I'll 100% change it, and from the other hand allows me to focus on making the actual product work without dabbling too much on naming.

**Comment by GabiGrin** [comment]
Renamed to "node" ✅
