### ISSUE TITLE
VSCode extension fails on version 1.74

### ISSUE THREAD

**Issue by GabiGrin** [flydelabs/flyde#37]
@GabiGrin I already have the extension, look what I get when I do new visual flow : 
![image](https://github.com/FlydeHQ/flyde/assets/68678258/8653b1fd-d148-4245-a8b3-901569816c47)

_Originally posted by @Xbz-24 in https://github.com/FlydeHQ/flyde/issues/35#issuecomment-1614337279_

**Comment by linonetwo** [comment]
I can Reproduce this on my Intel Mac. with many other extensions.

But on my girlfriend's m1 mac, With no other extensions, this won't happen.

**Comment by GabiGrin** [comment]
@linonetwo what VSCode version? `1.74.0` as well?

**Comment by linonetwo** [comment]
My failed is 1.79.2 , auto updated

```
Error: ENOENT: no such file or directory, stat '/Untitled-1'
```

**Comment by GabiGrin** [comment]
@linonetwo  very weird! can you share the full logs?

**Comment by linonetwo** [comment]
Sorry, It works well today. How to get the log? @Xbz-24 do you still have problem?
