### ISSUE TITLE
Error creating flow when VSCode is not set to a specific folder

### ISSUE THREAD

**Issue by sychris** [flydelabs/flyde#51]
Error creating flow: Error: EPERM: operation not permitted, open '\helloflow.flyde'

created a new folder to test this out
OS Name	Microsoft Windows 10 Pro
vs code extension v0.43.0
vs code version 1.81.1
tryed both new file from the file explorer vindow and file/new file

odd restarting and trying a few more times now its working...

**Comment by GabiGrin** [comment]
Thanks for the update @sychris!

**Comment by GabiGrin** [comment]
I'm reopening this issue after @sychris reported on the discord channel that it happens when VSCode is not open on a specific folder

**Comment by sjsepan3** [comment]
1) VSCodium, opened to folder:
~/Projects/Flyde/flyde1
containing (empty) file _helloflyde.flyde_ (I got the idea to use this name from the comments above by @sychris)

Perform:
Ctrl-Shift+P, 'Flyde: New Visual Flow', 'Hello World!', "NewFlow" (or "NewFlow.flyde"), Enter:

Error creating flow: Error: EACCES: permission denied, open '/NewFlow.flyde'
or respectively
Error creating flow: Error: EACCES: permission denied, open '/NewFlow.flyde.flyde'


2) Rename file to 
helloflyde.flyde

Perform:
Ctrl-Shift+P, 'Flyde: New Visual Flow', 'Hello World!', "NewFlow", Enter:
same error


3) open emptyfile helloflyde.flyde

Perform:
Ctrl-Shift+P, 'Flyde: New Visual Flow', 'Hello World!', "NewFlow", Enter:

Success!

------------
VSCodium:

Version: 1.85.2
Release: 24019
Commit: c8a36a69377856369f139f39ee56dd3838130fbf
Date: 2024-01-19T18:30:44.948Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-94-generic

------------
System:
  Kernel: 5.15.0-94-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Dell product: OptiPlex 5040 v: N/A serial: <superuser required> Chassis:
    type: 3 serial: <superuser required>
  Mobo: Dell model: 0R790T v: A00 serial: <superuser required> UEFI-[Legacy]: Dell v: 1.2.7
    date: 01/15/2016
Battery:
  Device-1: hidpp_battery_0 model: Logitech M570 serial: <filter> charge: 35% rechargeable: yes
    status: Discharging
CPU:
  Info: quad core model: Intel Core i5-6500 bits: 64 type: MCP smt: <unsupported> arch: Skylake-S
    rev: 3 cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 2303 high: 2700 min/max: 800/3600 cores: 1: 1277 2: 2547 3: 2690 4: 2700
    bogomips: 25599
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 535.154.05 pcie: speed: 8 GT/s
    lanes: 4 ports: active: none off: HDMI-A-1 empty: DVI-D-1 bus-ID: 01:00.0 chip-ID: 10de:1d01
    class-ID: 0300
  Device-2: Realtek RTL2838 DVB-T type: USB driver: usbfs bus-ID: 1-1:2 chip-ID: 0bda:2838
    class-ID: 0000 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x2160 s-dpi: 162 s-size: 602x341mm (23.7x13.4") s-diag: 692mm (27.2")
  Monitor-1: HDMI-0 res: 3840x2160 hz: 60 dpi: 163 size: 600x340mm (23.6x13.4")
    diag: 690mm (27.2")
  OpenGL: renderer: NVIDIA GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 535.154.05
    direct render: Yes
Audio:
  Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: Dell driver: snd_hda_intel
    v: kernel bus-ID: 00:1f.3 chip-ID: 8086:a170 class-ID: 0403
  Device-2: NVIDIA GP108 High Definition Audio driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 4 bus-ID: 01:00.1 chip-ID: 10de:0fb8 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-94-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I219-V vendor: Dell driver: e1000e v: kernel port: N/A bus-ID: 00:1f.6
    chip-ID: 8086:15b8 class-ID: 0200
  IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:
  Local Storage: total: 2.05 TiB used: 1.93 TiB (94.2%)
  ID-1: /dev/sda vendor: SanDisk model: SD8SBAT-256G-1006 size: 238.47 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: 1006 scheme: GPT
  ID-2: /dev/sdb vendor: Western Digital model: WDS100T2B0A-00SM50 size: 931.51 GiB
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: 20WD scheme: MBR
  ID-3: /dev/sdd type: USB vendor: Western Digital model: WD My Passport 25E1 size: 931.48 GiB
    type: N/A serial: <filter> rev: 1021 scheme: GPT
Partition:
  ID-1: / size: 233.62 GiB used: 62.68 GiB (26.8%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 47.2 MiB used: 6 MiB (12.8%) fs: vfat dev: /dev/sda2
  ID-3: /home size: 915.82 GiB used: 717.15 GiB (78.3%) fs: ext4 dev: /dev/sdb1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 1.8 MiB (0.1%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 16 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-1:2 info: Realtek RTL2838 DVB-T type: Video driver: usbfs interfaces: 2 rev: 2.0
    speed: 480 Mb/s power: 500mA chip-ID: 0bda:2838 class-ID: 0000 serial: <filter>
  Device-2: 1-3:3 info: 816820090226 type: Mass Storage driver: usb-storage interfaces: 1
    rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 3207:0300 class-ID: 0806 serial: <filter>
  Device-3: 1-5:4 info: Logitech Unifying Receiver type: Keyboard,Mouse,HID
    driver: logitech-djreceiver,usbhid interfaces: 3 rev: 2.0 speed: 12 Mb/s power: 98mA
    chip-ID: 046d:c52b class-ID: 0300
  Device-4: 1-9:5 info: Western Digital My Passport (WD20NMVW) type: Mass Storage
    driver: usb-storage interfaces: 1 rev: 2.1 speed: 480 Mb/s power: 500mA chip-ID: 1058:25e1
    class-ID: 0806 serial: <filter>
  Hub-2: 2-0:1 info: Super-speed hub ports: 10 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 29.8 C pch: 56.5 C mobo: 27.8 C gpu: nvidia temp: 36 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 86%
Repos:
  Packages: note: see --pkg apt: 3728
  Active apt repos in: /etc/apt/sources.list
    1: deb [trusted=yes] http: //www.raqsoft.com/raqesproc/update/debian/ /
  Active apt repos in: /etc/apt/sources.list.d/gambas-team-gambas3-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/gambas-team-gambas3-jammy.gpg] https: //ppa.launchpadcontent.net/gambas-team/gambas3/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/jonaski-strawberry-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/jonaski-strawberry-jammy.gpg] https: //ppa.launchpadcontent.net/jonaski/strawberry/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/krupkat-code-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/krupkat-code-jammy.gpg] https: //ppa.launchpadcontent.net/krupkat/code/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
  Active apt repos in: /etc/apt/sources.list.d/vscodium.list
    1: deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https: //download.vscodium.com/debs vscodium main
Info:
  Processes: 307 Uptime: 10h 29m wakeups: 30 Memory: 15.54 GiB used: 6.9 GiB (44.4%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 clang: 14.0.0-1ubuntu1.1
  Client: Unknown python client inxi: 3.3.13

**Comment by GabiGrin** [comment]
hey @sjsepan3, thanks so much for the update here.
I managed to recreate it on my end as well, using an empty folder to start with. 

Pushed a fixed on https://github.com/flydelabs/flyde-vscode/commit/2b00d52503dc965de3bc167717556eb2b2b43a5e

**Comment by GabiGrin** [comment]
Should be fixed on `v0.56.0.`! Thanks all for helpful reports

**Comment by sjsepan3** [comment]
Yes, v0.56.0 fixes it here too -- Thanks!

**Comment by GabiGrin** [comment]
Awesome, thanks for confirming 🙏
