### ISSUE TITLE
a flow in node form can be placed on its own flow

### ISSUE THREAD

**Issue by sychris** [flydelabs/flyde#55]
this seams dangerous cant think of a situation where this will lead to benefit and a lot of harm can be done.
recommending check on placement of node flow node:id != nodes node:id

**Comment by GabiGrin** [comment]
hey @sychris, that's a feature, not a bug.
It enables recursion, as seen in the website's Fibonacci example (https://play.flyde.dev/apps/70f1f36a-b10f-4a29-8e92-d29ec9422ba4).

What harm can it do in your opinion?
