### ISSUE TITLE
no apparent way to drag the graph around vscode

### ISSUE THREAD

**Issue by sychris** [flydelabs/flyde#60]
you can use the scroll wheel to scroll up and down but i would expect the middle mouse key or right click drag to move the canvas.
as a work around you can create a new value node throw it to the direction you would move the canvas and click center before deleting the node to move the canvas :)

**Comment by GabiGrin** [comment]
@sychris does it act differently in the playground?
Probably some adaptations to a mouse are needed. It's currently optimized for a trackpad 🙈

**Comment by danielo515** [comment]
I am experiencing similar issues in the playground in my mobile. Worth a separate issue?

**Comment by GabiGrin** [comment]
@danielo515  thanks for reporting
what mobile are you using? playground isn't optimized for mobile at all atm

**Comment by danielo515** [comment]
A Galaxy fold 5. It does not work in either screw

**Comment by GabiGrin** [comment]
@sychris this is now fixed. I totally misunderstood the severity of this issue as I used a trackpad (where scrolling 2d works)
Really sorry about that, hope you give Flyde a second chance!
