### ISSUE TITLE
using a namespace in user created nodes incorrect sorting

### ISSUE THREAD

**Issue by sychris** [flydelabs/flyde#63]
If namespace is designated in a .flyde.ts file and the namespace exists in the stdlib it places your node with the stdlib files like so:
![2023-09-07 06_05_06-saveAgentToDB flyde - flyde - Visual Studio Code](https://github.com/FlydeHQ/flyde/assets/4127743/16d26bf1-e045-4a73-86f6-c58894629963)

If you place them in a namespace that does not exist than they are not categorized at all

I would rather expect something like this:
![expected node list](https://github.com/FlydeHQ/flyde/assets/4127743/fffdf726-92fb-4145-b228-d9b366a14a0b)
where namespaces are created under current project

**Comment by GabiGrin** [comment]
@sychris interesting
do you see yourself using namespaces in your own projects? it was a quick way to categorize external packages but it definitely needs some more thought

**Comment by GabiGrin** [comment]
Closing this until more thought is invested on how do modules/namespaces work for user-world nodes in Flyde
