### ISSUE TITLE
Missing templates for issues

### ISSUE THREAD

**Issue by jacobra19** [flydelabs/flyde#64]
* missing templates for issues

react for example has different templates for different issue types
https://github.com/facebook/react/tree/main/.github/ISSUE_TEMPLATE

1.
<img width="1493" alt="image" src="https://github.com/flydelabs/flyde/assets/24259837/6bdeff50-698f-46af-8708-e794f83e0fed">

2.
<img width="1498" alt="image" src="https://github.com/flydelabs/flyde/assets/24259837/7667b461-aea8-4f16-a8f1-1c10dcc09c67">

@GabiGrin i can take it

**Comment by GabiGrin** [comment]
@jacobra19 I'd love help with that. TBH, there are not enough issues for me to see a pattern yet, so I'd recommend starting a s simple as possible and we can re-adapt once there are 100+ issues

**Comment by sychris** [comment]
Things that really need to be in the template could include if there using the vs extension or web site, version number and operating system / browser.

**Comment by GabiGrin** [comment]
Addressed in #90
