### ISSUE TITLE
Missing "getting started" as oss dev (not user)

### ISSUE THREAD

**Issue by jacobra19** [flydelabs/flyde#70]
* easy entry point for new contributors to get up and running with the project
* design diagrams of the general architecture might be helpful to understand what's is going on

how?
* contribution guide
  * setup locally: prerequisite, yarn, yarn build, cd editor, yarn start, and so on...
  * How to contribute to the project? 
* high level overview of the packages and the project structure

**Comment by GabiGrin** [comment]
Addressed in #90
